"""PDF generation from HTML content."""

from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader
from weasyprint import CSS, HTML

from .config import BuildConfig


class PDFGenerator:
    """Generates PDF documents from HTML content."""

    def __init__(self, config: BuildConfig):
        """
        Initialize PDF generator.

        Args:
            config: Build configuration
        """
        self.config = config

        # Setup Jinja2 template environment
        self.template_env = Environment(
            loader=FileSystemLoader(str(config.template_dir)),
            autoescape=True,
        )

    def _load_css(self) -> list[CSS]:
        """
        Load CSS stylesheets for PDF.

        Returns:
            List of CSS objects
        """
        css_files = []
        css_path = self.config.template_dir / "pdf_style.css"

        if css_path.exists():
            css_files.append(CSS(filename=str(css_path)))

        return css_files

    def _render_cover_page(self) -> str:
        """
        Render cover page HTML.

        Returns:
            Cover page HTML content
        """
        try:
            template = self.template_env.get_template("cover.html")
            return template.render(
                project={
                    "name": self.config.project_name,
                    "author": self.config.project_author,
                    "version": self.config.project_version,
                    "license": self.config.project_license,
                },
                build_date=datetime.now().strftime("%B %d, %Y"),
            )
        except Exception as e:
            # Fallback to simple cover if template fails
            return f"""
            <html>
            <body>
                <div style="text-align: center; padding-top: 200px;">
                    <h1>{self.config.project_name}</h1>
                    <p>Version {self.config.project_version}</p>
                    <p>{self.config.project_author}</p>
                    <p>{datetime.now().strftime("%B %d, %Y")}</p>
                </div>
            </body>
            </html>
            """

    def _build_full_html(self, html_content: str) -> str:
        """
        Build complete HTML document with cover, TOC, and content.

        Args:
            html_content: Main content HTML

        Returns:
            Complete HTML document
        """
        # Load CSS inline for standalone HTML
        css_path = self.config.template_dir / "pdf_style.css"
        css_content = ""
        if css_path.exists():
            with open(css_path, encoding="utf-8") as f:
                css_content = f.read()

        # Build complete HTML
        full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.config.project_name}</title>
    <style>{css_content}</style>
</head>
<body>
    <div class="cover page-break">
        <h1>{self.config.project_name}</h1>
        <div class="version">Version {self.config.project_version}</div>
        <div class="author">{self.config.project_author}</div>
        <div class="date">{datetime.now().strftime("%B %d, %Y")}</div>
        <div class="license">{self.config.project_license}</div>
    </div>

    <div class="content">
        {html_content}
    </div>

    <div class="page-break"></div>
    <div class="footer">
        <p>Generated by Corona Digital CX Documentation Build System</p>
        <p>Licensed under {self.config.project_license}</p>
    </div>
</body>
</html>
"""
        return full_html

    def generate_pdf(self, html_content: str, output_path: Path) -> Path:
        """
        Generate PDF from HTML content.

        Args:
            html_content: HTML content to convert
            output_path: Output PDF file path

        Returns:
            Path to generated PDF file
        """
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Build complete HTML document
        full_html = self._build_full_html(html_content)

        # Load CSS stylesheets
        stylesheets = self._load_css()

        # Generate PDF
        html_doc = HTML(string=full_html, base_url=str(Path.cwd()))
        html_doc.write_pdf(
            str(output_path),
            stylesheets=stylesheets,
        )

        return output_path

    def generate_html(self, html_content: str, output_path: Path) -> Path:
        """
        Generate standalone HTML file.

        Args:
            html_content: HTML content
            output_path: Output HTML file path

        Returns:
            Path to generated HTML file
        """
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Build complete HTML document
        full_html = self._build_full_html(html_content)

        # Write to file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(full_html)

        return output_path

    def get_output_paths(self) -> tuple[Path, Path]:
        """
        Get default output paths for PDF and HTML.

        Returns:
            Tuple of (pdf_path, html_path)
        """
        output_dir = self.config.output_dir
        base_name = self.config.output_name

        pdf_path = output_dir / f"{base_name}.pdf"
        html_path = output_dir / f"{base_name}.html"

        return pdf_path, html_path
