"""PDF generation from HTML content."""

from datetime import datetime
from pathlib import Path

from jinja2 import Environment, FileSystemLoader
from weasyprint import CSS, HTML

from .config import BuildConfig


class PDFGenerator:
    """Generates PDF documents from HTML content."""

    def __init__(self, config: BuildConfig):
        """
        Initialize PDF generator.

        Args:
            config: Build configuration
        """
        self.config = config

        # Setup Jinja2 template environment
        self.template_env = Environment(
            loader=FileSystemLoader(str(config.template_dir)),
            autoescape=True,
        )

    def _load_css(self) -> list[CSS]:
        """
        Load CSS stylesheets for PDF.

        Returns:
            List of CSS objects
        """
        css_files = []
        css_path = self.config.template_dir / "pdf_style.css"

        if css_path.exists():
            css_files.append(CSS(filename=str(css_path)))

        return css_files

    def _render_cover_page(self) -> str:
        """
        Render cover page HTML.

        Returns:
            Cover page HTML content
        """
        try:
            template = self.template_env.get_template("cover.html")
            return template.render(
                project={
                    "name": self.config.project_title,
                    "author": self.config.project_author,
                    "version": self.config.project_version,
                    "license": self.config.project_license,
                },
                build_date=datetime.now().strftime("%B %d, %Y"),
            )
        except Exception as e:
            # Fallback to simple cover if template fails
            return f"""
            <html>
            <body>
                <div style="text-align: center; padding-top: 200px;">
                    <h1>{self.config.project_title}</h1>
                    <p>Version {self.config.project_version}</p>
                    <p>{self.config.project_author}</p>
                    <p>{datetime.now().strftime("%B %d, %Y")}</p>
                </div>
            </body>
            </html>
            """

    def _build_pdf_html(self, html_content: str) -> str:
        """
        Build complete HTML document with cover, TOC, and content.

        Args:
            html_content: Main content HTML

        Returns:
            Complete HTML document
        """
        # Load PDF CSS inline for rendering
        css_path = self.config.template_dir / "pdf_style.css"
        css_content = ""
        if css_path.exists():
            with open(css_path, encoding="utf-8") as f:
                css_content = f.read()

        # Build complete HTML
        full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.config.project_title}</title>
    <style>{css_content}</style>
</head>
<body>
    <div class="cover page-break">
        <h1>{self.config.project_title}</h1>
        <div class="version">Version {self.config.project_version}</div>
        <div class="author">{self.config.project_author}</div>
        <div class="date">{datetime.now().strftime("%B %d, %Y")}</div>
        <div class="license">{self.config.project_license}</div>
    </div>

    <div class="content">
        {html_content}
    </div>

    <div class="page-break"></div>
    <div class="footer">
        <p>Generated by Corona Digital CX Documentation Build System</p>
        <p>Licensed under {self.config.project_license}</p>
    </div>
</body>
</html>
"""
        return full_html

    def _build_web_html(self, html_content: str) -> str:
        """
        Build standalone HTML optimized for browser reading.

        Args:
            html_content: Main content HTML

        Returns:
            Complete HTML document
        """
        css_path = self.config.template_dir / "web_style.css"
        if not css_path.exists():
            css_path = self.config.template_dir / "pdf_style.css"

        css_content = ""
        if css_path.exists():
            with open(css_path, encoding="utf-8") as f:
                css_content = f.read()

        full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.config.project_title}</title>
    <meta name="description" content="{self.config.get('project.description', self.config.project_title)}">
    <style>{css_content}</style>
</head>
<body>
    <div class="site-shell">
        <header class="hero">
            <div class="hero__eyebrow">Open Standard</div>
            <h1>{self.config.project_title}</h1>
            <p class="hero__summary">{self.config.get('project.description', self.config.project_title)}</p>
            <div class="hero__meta">
                <span>Version {self.config.project_version}</span>
                <span>{self.config.project_author}</span>
                <span>{self.config.project_license}</span>
            </div>
        </header>

        <main class="document-frame">
            <div class="document-layout">
                <aside class="toc-shell" aria-label="Document table of contents">
                    <div class="toc-card">
                        <div class="toc-card__eyebrow">Navigate</div>
                        <div class="toc-card__title">On This Page</div>
                        <nav id="table-of-contents" class="toc-nav"></nav>
                    </div>
                </aside>

                <article class="content prose" id="document-content">
                    {html_content}
                </article>
            </div>
        </main>

        <footer class="site-footer">
            <p>Generated by Corona Digital CX Documentation Build System</p>
            <p>Licensed under {self.config.project_license}</p>
        </footer>
    </div>
    <script>
    (() => {{
        const root = document.getElementById("document-content");
        const nav = document.getElementById("table-of-contents");
        if (!root || !nav) return;

        const headings = [...root.querySelectorAll("h1[id], h2[id], h3[id]")];
        if (!headings.length) {{
            nav.parentElement.style.display = "none";
            return;
        }}

        const list = document.createElement("ol");
        list.className = "toc-list";

        for (const heading of headings) {{
            const item = document.createElement("li");
            const level = heading.tagName.toLowerCase();
            item.className = `toc-item toc-item--${{level}}`;

            const link = document.createElement("a");
            link.href = `#${{heading.id}}`;
            link.textContent = heading.textContent.trim();
            item.appendChild(link);
            list.appendChild(item);
        }}

        nav.appendChild(list);

        const links = [...nav.querySelectorAll("a")];
        const byId = new Map(links.map((link) => [link.getAttribute("href")?.slice(1), link]));

        const observer = new IntersectionObserver(
            (entries) => {{
                const visible = entries
                    .filter((entry) => entry.isIntersecting)
                    .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);

                if (!visible.length) return;

                const activeId = visible[0].target.id;
                for (const link of links) {{
                    link.classList.toggle("is-active", link.getAttribute("href") === `#${{activeId}}`);
                }}
            }},
            {{
                rootMargin: "-20% 0px -70% 0px",
                threshold: [0, 1],
            }},
        );

        for (const heading of headings) observer.observe(heading);
    }})();
    </script>
</body>
</html>
"""
        return full_html

    def generate_pdf(self, html_content: str, output_path: Path) -> Path:
        """
        Generate PDF from HTML content.

        Args:
            html_content: HTML content to convert
            output_path: Output PDF file path

        Returns:
            Path to generated PDF file
        """
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Build complete HTML document
        full_html = self._build_pdf_html(html_content)

        # Load CSS stylesheets
        stylesheets = self._load_css()

        # Generate PDF
        html_doc = HTML(string=full_html, base_url=str(Path.cwd()))
        html_doc.write_pdf(
            str(output_path),
            stylesheets=stylesheets,
        )

        return output_path

    def generate_html(self, html_content: str, output_path: Path) -> Path:
        """
        Generate standalone HTML file.

        Args:
            html_content: HTML content
            output_path: Output HTML file path

        Returns:
            Path to generated HTML file
        """
        # Ensure output directory exists
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Build complete HTML document
        full_html = self._build_web_html(html_content)

        # Write to file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(full_html)

        return output_path

    def get_output_paths(self) -> tuple[Path, Path]:
        """
        Get default output paths for PDF and HTML.

        Returns:
            Tuple of (pdf_path, html_path)
        """
        output_dir = self.config.output_dir
        base_name = self.config.output_name

        pdf_path = output_dir / f"{base_name}.pdf"
        html_path = output_dir / f"{base_name}.html"

        return pdf_path, html_path
